// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vT.eCoffeeShop.Infrastructure.Contexts.OrderContexts;

#nullable disable

namespace vT.eCoffeeShop.Infrastructure.Migrations
{
    [DbContext(typeof(SqlDbContextOrder))]
    partial class SqlDbContextOrderModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vT.eCoffeeShop.Infrastructure.Models.CoffeeItemDto", b =>
                {
                    b.Property<Guid>("CoffeeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CoffeeItemId");

                    b.ToTable("CoffeeItems", "cfe");

                    b.HasData(
                        new
                        {
                            CoffeeItemId = new Guid("dfeba5cf-393f-4587-9a26-291577e11198"),
                            Description = "Strong and bold coffee.",
                            ImageUrl = "assets/img/Espresso.jpg",
                            IsAvailable = true,
                            Name = "Espresso",
                            Price = 102.50m,
                            Weight = 60m
                        },
                        new
                        {
                            CoffeeItemId = new Guid("4277459d-5dfb-48c6-8cfc-13f8c978b111"),
                            Description = "Smooth coffee with milk.",
                            ImageUrl = "assets/img/Latte.jpg",
                            IsAvailable = true,
                            Name = "Latte",
                            Price = 123.50m,
                            Weight = 240m
                        },
                        new
                        {
                            CoffeeItemId = new Guid("187cd072-72f2-433e-9e69-1735a33ce036"),
                            Description = "Espresso with steamed milk foam.",
                            ImageUrl = "assets/img/Cappuccino.jpg",
                            IsAvailable = true,
                            Name = "Cappuccino",
                            Price = 75.75m,
                            Weight = 190m
                        },
                        new
                        {
                            CoffeeItemId = new Guid("67ea6e2d-4c7e-43fa-8341-c0fc00235e71"),
                            Description = "Espresso diluted with hot water.",
                            ImageUrl = "assets/img/Americano.jpg",
                            IsAvailable = false,
                            Name = "Americano",
                            Price = 112.00m,
                            Weight = 200m
                        },
                        new
                        {
                            CoffeeItemId = new Guid("ac3ba645-ea57-4ea5-beb8-35b2bac1045a"),
                            Description = "Espresso with steamed milk and chocolate syrup.",
                            ImageUrl = "assets/img/Mocha.jpg",
                            IsAvailable = true,
                            Name = "Mocha",
                            Price = 144.00m,
                            Weight = 220m
                        });
                });

            modelBuilder.Entity("vT.eCoffeeShop.Infrastructure.Models.CustomerDto", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", "cfe");
                });
#pragma warning restore 612, 618
        }
    }
}
